In [2]:
import numpy as np

In [ ]:
#1
arr = np.array([1,7,13,105])
print(f"Size of array ={arr.nbytes}")

               

In [ ]:
#2
arr1 = np.array([1,7,13,105])
arr2 = np.array([2,7,12,105])
for i in range(len(arr1)):
    
    if arr1[i] == arr2[i]:
        print(f"{arr1[i]} is equal to {arr2[i]}")
    elif arr1[i] > arr2[i]:
        print(f"{arr1[i]} is greater than {arr2[i]}")
    else:
        print(f"{arr1[i]} is less than {arr2[i]}")


        

In [ ]:
#3
arr = np.zeros(10)
print(arr)
arr1 = np.ones(10)
print(arr1)
arr2 = 5 * arr1
print(arr2)
arr3 = 10 * arr1
print(arr3)
arr4 = 20 * arr1
print(arr4)
arr5 = 50 * arr1
print(arr5)
  


In [ ]:
#4
arr =np.arange(30,71)
print(arr)


In [ ]:
#5
arr1 =np.arange(50,96)
print(arr1)

In [ ]:
#6
arr =np.arange(20,80,2)
print(arr)

In [ ]:
#7
arr =np.arange(21,80,2)
print(arr)

In [31]:
#8
arr =np.random.randint(10,40,15)
print(arr)


[27 20 33 11 30 16 24 33 25 17 15 39 24 17 30]


In [37]:
#9
arr = np.random.randint(30,50,10)
print(arr)

[49 44 49 46 36 33 44 42 31 48]


In [38]:
#10
arr = np.random.randint(50,90,20)
print(arr)

[79 89 83 73 71 51 87 83 88 61 81 78 88 82 79 53 80 50 65 74]


In [9]:
#11
def Array_Generation():
    size = int(input("Enter the size of the array: "))
    elements1 = []
    elements2 = []
    
    for i in range(size):
        element = float(input(f"Enter element of arr1 {i+1}: "))
        elements1.append(element)
    for i in range(size):
        element = float(input(f"Enter element of arr2 {i+1}: "))
        elements2.append(element)
    arr1 = np.array(elements1)
    arr2 = np.array(elements2)
    arr3 = arr1 + arr2
    arr4 = arr1 - arr2
    arr5 = arr1 * arr2
    arr6 = arr1 / arr2
    print(arr3)
    print(arr4)
    print(arr5)
    print(arr6)
Array_Generation()









Enter the size of the array:  5
Enter element of arr1 1:  10
Enter element of arr1 2:  20
Enter element of arr1 3:  30
Enter element of arr1 4:  40
Enter element of arr1 5:  50
Enter element of arr2 1:  1
Enter element of arr2 2:  2
Enter element of arr2 3:  3
Enter element of arr2 4:  4
Enter element of arr2 5:  5


[11. 22. 33. 44. 55.]
[ 9. 18. 27. 36. 45.]
[ 10.  40.  90. 160. 250.]
[10. 10. 10. 10. 10.]


In [16]:
#12
arr = np.arange(10,22)
arr = arr.reshape(3,4)
print(arr)




[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [25]:
#13
identity_matrix = np.zeros((3, 3))

for i in range(3):
    identity_matrix[i, i] = 1

print("3x3 Identity Matrix:")
print(identity_matrix)



3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#14
arr = np.arange(10,22)
arr = arr.reshape(3,4)

print(f"No of rows: {arr.shape[0]}")
print(f"No of columns: {arr.shape[1]}")

# for i in range(len(arr)):
#     if i 


No of rows: 3
No of columns: 4


In [14]:
#15
matrix = np.zeros((5, 5))

for i in range(5):
        matrix[i,i] = i+1
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [22]:
#16
element =np.random.randint(1,100,27)
arr = element.reshape(3,3,3)
print(arr)




[[[75 34 50]
  [26 39 33]
  [69 30 97]]

 [[64 96 72]
  [73 88 11]
  [26 84 59]]

 [[59 58 54]
  [74  6 92]
  [68  8 54]]]


In [23]:
#17
element =np.random.randint(1,100,24)
arr = element.reshape(2,3,4)
print(arr)

[[[24 36 31 37]
  [35 69 98 50]
  [31 63 62 64]]

 [[95 29 85 27]
  [21 83 70 82]
  [90 43 12 50]]]


In [32]:
#18
element = [1,2,3,4,5,6,7,8,9]
arr = np.array(element)
print(f"type :{type(arr)}")
print(arr)

type :<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [36]:
#19
matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [38]:
#20
array = np.arange(12,38)
print(f"type :{type(array)}")
print(array)

type :<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [42]:
#21
arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print(f"Original array: {arr}")
print(f"Reversed array: {reversed_arr}")


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [44]:
#22
num = 10
print(f"type : {type(num)}")
num_f = float(num)
print(f"type : {type(num_f)}")


type : <class 'int'>
type : <class 'float'>


In [45]:
#23
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
print(arr)

[1 2 3 4 5]


In [46]:
#24
arr = np.array([10, 20, 30, 40, 50])
remainder = np.remainder(arr, 3)
print(remainder)

[1 2 0 1 2]


In [49]:
#25
element = np.arange(20,50)
array = np.array(element)
remainder =np.remainder(array,3)
print(remainder)

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
